# pcp.nix
#
# Performance Co-Pilot — always-on performance monitoring + archive logging.
#
# Adapted from the PCP project's upstream NixOS module (build/nix/nixos-module.nix)
# for this single-host repo:
#   - the `pcp` specialArgs plumbing is dropped; the package comes from
#     ./packages/pcp via callPackage
#   - the microvm/test `constants.nix` is reduced to the handful of values the
#     service config actually needs (inlined below)
#   - self-activating for atreides: `services.pcp.enable` defaults to true here,
#     with a desktop-appropriate profile set at the bottom of this file
#
# Why on a desktop: pmlogger records the full metric set to on-disk archives
# continuously, so intermittent, after-the-fact incidents (kwin/GPU context
# loss, plasmashell SIGSEGVs, portal failures) can be replayed with
# `pcp atop -a <archive>`, `pmrep -a <archive> ...`, `pmchart`, etc. — the
# "what was the box doing at 3am" question that live htop/btop can't answer.
#
# Everything stays on loopback: the firewall is NOT opened, so pmcd (44321) and
# pmproxy (if enabled) are reachable only by local clients. Archives are culled
# daily by pmlogger_daily.
#
{ config, pkgs, lib, ... }:
with lib;
let
  cfg = config.services.pcp;

  # ─── Inlined constants (subset of upstream build/nix/constants.nix) ──────
  constants = {
    pmdaDomains = {
      pmcd = 2;    # src/pmdas/pmcd/domain.h
      linux = 60;  # src/pmdas/linux/domain.h
    };
    paths = {
      logDir = "/var/log/pcp";
      varDir = "/var/lib/pcp";
      tmpDir = "/var/lib/pcp/tmp";
      runDir = "/run/pcp";
      archiveDir = "/var/log/pcp/pmlogger";
    };
    ports = {
      pmcd = 44321;
      pmproxy = 44322;
    };
  };

  pcpConf = "${cfg.package}/share/pcp/etc/pcp.conf";
  pcpDir = "${cfg.package}/share/pcp";

  # ─── PMDA Configuration ─────────────────────────────────────────────────
  # Generate pmcd.conf entries for additional PMDAs
  pmdaEntries = concatStringsSep "\n" (mapAttrsToList (name: pmda:
    if pmda.type == "dso" then
      "${name}\t${toString pmda.domain}\tdso\t${pmda.init}\t${pmda.path}"
    else
      "${name}\t${toString pmda.domain}\t${pmda.type}\t${pmda.flags}\t${pmda.command}"
  ) cfg.pmdas);

  # Generate pmcd.conf with base PMDAs + additional ones.
  # On Linux the base is: linux (60) + pmcd (2), both as DSO.
  pmcdConf = pkgs.writeText "pmcd.conf" ''
    #
    # Performance Co-Pilot PMDA Configuration
    # Generated by NixOS - do not edit directly
    #
    # Format: name domain_id type init_func/flags path/command
    #

    # ─── Base Platform PMDAs ──────────────────────────────────────────────
    # Linux kernel metrics (DSO for performance)
    linux	${toString constants.pmdaDomains.linux}	dso	linux_init	${cfg.package}/var/lib/pcp/pmdas/linux/pmda_linux.so

    # PMCD internal metrics (DSO)
    pmcd	${toString constants.pmdaDomains.pmcd}	dso	pmcd_init	${cfg.package}/var/lib/pcp/pmdas/pmcd/pmda_pmcd.so

    ${optionalString (pmdaEntries != "") ''
        # ─── Additional PMDAs ─────────────────────────────────────────────────
        ${pmdaEntries}
    ''}
  '';

  # Custom pmie rules, materialised as a store file for the dedicated instance.
  customPmieFile = pkgs.writeText "pcp-atreides.pmie" cfg.pmieConfig;

  # Environment for PCP services + interactive CLI tools.
  # Override PCP_*_DIR to mutable system paths (the store copies are read-only).
  pcpEnv = {
    PCP_CONF = pcpConf;
    PCP_DIR = pcpDir;
    PCP_PMCDCONF_PATH = "/etc/pcp/pmcd/pmcd.conf";
    PCP_LOG_DIR = constants.paths.logDir;
    PCP_VAR_DIR = constants.paths.varDir;
    PCP_TMP_DIR = constants.paths.tmpDir;
    PCP_RUN_DIR = constants.paths.runDir;
    PCP_ARCHIVE_DIR = constants.paths.archiveDir;
    # Override hardcoded /bin/pwd path in shell scripts (see shell-portable-pwd.patch)
    PWDCMND = "pwd";
  };

  # ─── Shared systemd hardening ────────────────────────────────────────
  baseHardening = {
    PrivateTmp = true;
    ProtectHome = true;
    ProtectControlGroups = true;
    ProtectKernelModules = true;
    NoNewPrivileges = true;
    RestrictRealtime = true;
    LockPersonality = true;
  };

  hasBccPmda = cfg.pmdas ? bcc;
  pmcdHardening = recursiveUpdate baseHardening (
    optionalAttrs (cfg.relaxedPermissions || hasBccPmda) ({
      CapabilityBoundingSet = []
        ++ optionals cfg.relaxedPermissions [
          "CAP_DAC_READ_SEARCH"  # For reading /proc of other users' processes
          "CAP_SYS_PTRACE"       # For pmdaproc process inspection
        ]
        ++ optionals hasBccPmda [
          "CAP_SYS_ADMIN"        # BPF syscall (kernel < 5.8)
          "CAP_BPF"              # BPF syscall (kernel >= 5.8)
          "CAP_PERFMON"          # Perf events (kernel >= 5.8)
          "CAP_SYS_PTRACE"       # Read /proc of other processes
          "CAP_DAC_READ_SEARCH"  # Access kernel symbols
        ];
    } // optionalAttrs hasBccPmda {
      AmbientCapabilities = [
        "CAP_SYS_ADMIN"
        "CAP_BPF"
        "CAP_PERFMON"
        "CAP_SYS_PTRACE"
        "CAP_DAC_READ_SEARCH"
      ];
      NoNewPrivileges = false;
    })
  );

  pmproxyHardening = baseHardening;

  ipFiltering = optionalAttrs (cfg.allowedNetworks != []) {
    IPAddressAllow = cfg.allowedNetworks;
    IPAddressDeny = "any";
  };

in
{
  # ═══════════════════════════════════════════════════════════════════════
  # Options interface (kept compatible with upstream services.pcp.*)
  # ═══════════════════════════════════════════════════════════════════════

  options.services.pcp = {
    enable = mkEnableOption "Performance Co-Pilot monitoring services";

    package = mkOption {
      type = types.package;
      default = pkgs.callPackage ./packages/pcp { };
      defaultText = literalExpression "pkgs.callPackage ./packages/pcp { }";
      description = "The PCP package to use.";
    };

    preset = mkOption {
      type = types.enum [ "standalone" "minimal" "custom" ];
      default = "standalone";
      description = ''
        Deployment preset:
        - standalone: pmcd + pmlogger + pmie + pmproxy
        - minimal: only pmcd (remote collection target)
        - custom: configure each component manually
      '';
    };

    pmlogger.enable = mkOption {
      type = types.bool;
      default = cfg.preset == "standalone";
      defaultText = literalExpression ''config.services.pcp.preset == "standalone"'';
      description = "Enable pmlogger (archive logger).";
    };

    pmie.enable = mkOption {
      type = types.bool;
      default = cfg.preset == "standalone";
      defaultText = literalExpression ''config.services.pcp.preset == "standalone"'';
      description = "Enable pmie (inference engine).";
    };

    pmproxy.enable = mkOption {
      type = types.bool;
      default = cfg.preset == "standalone";
      defaultText = literalExpression ''config.services.pcp.preset == "standalone"'';
      description = "Enable pmproxy (REST API gateway; needed for pmseries/Grafana).";
    };

    allowedNetworks = mkOption {
      type = types.listOf types.str;
      default = [];
      example = [ "10.177.0.0/24" "127.0.0.0/8" ];
      description = "IP ranges allowed to connect to pmcd/pmproxy (systemd IPAddressAllow).";
    };

    openFirewall = mkOption {
      type = types.bool;
      default = false;
      description = "Open firewall ports for pmcd/pmproxy. Off = loopback-only.";
    };

    relaxedPermissions = mkOption {
      type = types.bool;
      default = false;
      description = ''
        Grant pmcd CAP_DAC_READ_SEARCH + CAP_SYS_PTRACE so introspective PMDAs
        (e.g. pmdaproc) can read other users' /proc entries.
      '';
    };

    pmdas = mkOption {
      type = types.attrsOf (types.submodule {
        options = {
          domain = mkOption {
            type = types.int;
            description = "PMDA domain number (unique identifier, 0-511)";
          };
          type = mkOption {
            type = types.enum [ "dso" "pipe" "socket" ];
            default = "pipe";
            description = "PMDA type: dso (shared library), pipe (spawned process), socket (daemon)";
          };
          flags = mkOption {
            type = types.str;
            default = "binary";
            description = "PMDA flags (e.g., 'binary', 'binary notready')";
          };
          command = mkOption {
            type = types.str;
            description = "For pipe/socket PMDAs: command to execute";
          };
          init = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = "For DSO PMDAs: init function name";
          };
          path = mkOption {
            type = types.nullOr types.str;
            default = null;
            description = "For DSO PMDAs: path to shared library";
          };
        };
      });
      default = {};
      description = "Additional PMDAs to register with pmcd (appended to pmcd.conf).";
    };

    pmieConfig = mkOption {
      type = types.lines;
      default = "";
      description = ''
        Custom pmie rule text. When non-empty (and pmie is enabled), it is run
        as a dedicated pmie instance (`pmie-rules.service`), independent of
        pmie_check's default rule set. Rule `print` actions land in the journal
        (`journalctl -u pmie-rules`).
      '';
    };

    hotprocPredicate = mkOption {
      type = types.str;
      default = "";
      example = ''(fname == ".kwin_wayland-w" || fname == ".plasmashell-wr")'';
      description = ''
        hotproc predicate (proc PMDA) selecting which processes get tracked in
        the `hotproc.*` metric tree. Applied at runtime via `pmstore
        hotproc.control.config` by `pcp-hotproc.service`. Requires the `proc`
        PMDA to be registered in `services.pcp.pmdas`. Best-effort: if it does
        not take, `hotproc.*` simply reports no instances.
      '';
    };
  };

  # ═══════════════════════════════════════════════════════════════════════
  # Implementation
  # ═══════════════════════════════════════════════════════════════════════

  config = mkMerge [

    # ─── atreides host profile ────────────────────────────────────────────
    # Self-activating: local always-on collector + archive logger + inference,
    # plus pmproxy (REST/pmseries) for the Grafana stack in ./pcp-grafana.nix.
    # Everything stays on loopback — openFirewall off (pmproxy 44322 local-only).
    {
      services.pcp = {
        enable = mkDefault true;
        preset = mkDefault "standalone";
        pmproxy.enable = mkDefault true;
        openFirewall = mkDefault false;

        # proc PMDA (pipe) — needed for per-process + hotproc metrics used by
        # the desktop RSS rule below.
        pmdas.proc = {
          domain = 3;
          type = "pipe";
          flags = "binary";
          command = "${cfg.package}/libexec/pcp/pmdas/proc/pmdaproc -d 3";
        };

        # Track just the compositor/shell in the hotproc.* tree. NixOS wraps
        # these binaries, so /proc comm is truncated to 15 chars with a leading
        # dot (".kwin_wayland-w" = the real compositor, ".plasmashell-wr"); the
        # separate ".kwin_wayland_w" is only the small launcher wrapper.
        # Matching MUST be exact `fname ==` on that comm. Two things that look
        # right but silently match nothing (verified: nprocs stays 0): a
        # `psargs ~ /…/` regex never reaches the binary name, which sits past the
        # /nix/store/<hash>- prefix that hotproc only inspects the head of; and
        # hotproc's `~` operator is itself broken here — it fails even on a
        # leading fname substring while `==` works. Wayland session only; an X11
        # run would additionally need the truncated ".kwin_x11-wrapp" comm.
        hotprocPredicate = mkDefault
          ''(fname == ".plasmashell-wr" || fname == ".kwin_wayland-w")'';

        # Memory-pressure + desktop-process alerts. These fire on the actual
        # trigger conditions of the intermittent kwin/plasmashell incidents.
        # (GPU-VRAM alerting is a planned follow-up — the nvidia PMDA needs
        # extra packaging that has to be validated against a live collector.)
        pmieConfig = mkDefault ''
          // pcp-atreides.pmie — watch:  journalctl -u pmie-rules -f
          delta = 30 sec;

          // ── System-wide memory pressure (linux PMDA) ──────────────────────
          low_memory =
              ( 100 * mem.util.available / mem.physmem ) < 8
              -> print "LOW MEMORY: %v%% of RAM available";

          mem_psi =
              kernel.all.pressure.memory.some.avg #'10 second' > 20
              -> print "MEMORY STALL: PSI some/10s = %v%%";

          majflt =
              rate(mem.vmstat.pgmajfault) > 2000
              -> print "PAGING STORM: %v major faults/sec";

          swapout =
              rate(mem.vmstat.pswpout) > 1000
              -> print "SWAP THRASH: %v pages/sec swapped out";

          oom =
              rate(mem.vmstat.oom_kill) > 0
              -> print "OOM KILL: kernel killed a process";

          // ── Compositor / shell RSS (proc PMDA + hotproc predicate) ────────
          // Fires if a tracked desktop process exceeds 4 GiB RSS (4194304 KiB).
          desktop_rss =
              hotproc.psinfo.rss > 4194304
              -> print "DESKTOP PROC RSS HIGH: %i using %v KiB";
        '';
      };
    }

    (mkIf cfg.enable {
      environment.systemPackages = [ cfg.package ];

      users.users.pcp = {
        isSystemUser = true;
        group = "pcp";
        description = "Performance Co-Pilot daemon user";
      };
      users.groups.pcp = {};

      environment.variables = pcpEnv;

      systemd.tmpfiles.rules = [
        # Runtime directories
        "d /var/lib/pcp          0755 pcp pcp -"
        "d /var/lib/pcp/tmp      0775 pcp pcp -"
        "d /var/log/pcp          0755 pcp pcp -"
        "d /var/log/pcp/pmcd     0755 root root -"
        "d /var/log/pcp/pmlogger 0775 pcp pcp -"
        "d /var/log/pcp/pmie     0775 pcp pcp -"
        "d /var/log/pcp/pmproxy  0775 pcp pcp -"
        "d /run/pcp              0775 pcp pcp -"

        # Symlinks to read-only store paths (PMNS, PMDAs)
        "L+ /var/lib/pcp/pmns    - - - - ${cfg.package}/var/lib/pcp/pmns"
        "L+ /var/lib/pcp/pmdas   - - - - ${cfg.package}/var/lib/pcp/pmdas"
        "L+ /var/lib/pcp/pmcd    - - - - ${cfg.package}/var/lib/pcp/pmcd"

        # Config directory structure - mix of read-only symlinks and writable dirs
        "d  /var/lib/pcp/config              0755 pcp pcp -"
        "L+ /var/lib/pcp/config/derived      - - - - ${cfg.package}/var/lib/pcp/config/derived"
        "L+ /var/lib/pcp/config/pmafm        - - - - ${cfg.package}/var/lib/pcp/config/pmafm"
        "L+ /var/lib/pcp/config/pmieconf     - - - - ${cfg.package}/var/lib/pcp/config/pmieconf"
        "L+ /var/lib/pcp/config/pmlogconf    - - - - ${cfg.package}/var/lib/pcp/config/pmlogconf"
        "L+ /var/lib/pcp/config/pmlogredact  - - - - ${cfg.package}/var/lib/pcp/config/pmlogredact"
        "L+ /var/lib/pcp/config/pmlogrewrite - - - - ${cfg.package}/var/lib/pcp/config/pmlogrewrite"
        # Writable directories for runtime-generated configs (pmlogconf writes config.default here)
        "d  /var/lib/pcp/config/pmda         0775 pcp pcp -"
        "d  /var/lib/pcp/config/pmie         0775 pcp pcp -"
        "d  /var/lib/pcp/config/pmlogger     0775 pcp pcp -"
        # Static pmlogger configs as symlinks
        "L+ /var/lib/pcp/config/pmlogger/config.pmstat  - - - - ${cfg.package}/var/lib/pcp/config/pmlogger/config.pmstat"
        "L+ /var/lib/pcp/config/pmlogger/options.pmstat - - - - ${cfg.package}/var/lib/pcp/config/pmlogger/options.pmstat"

        # FHS-compatible symlinks (so `cat /etc/pcp.conf`, `. /etc/pcp.env` work)
        "L+ /etc/pcp.conf        - - - - ${cfg.package}/share/pcp/etc/pcp.conf"
        "L+ /etc/pcp.env         - - - - ${cfg.package}/share/pcp/etc/pcp.env"

        # /etc/pcp structure (real dir so pmcd.conf can be a writable copy)
        "d  /etc/pcp             0755 root root -"
        "d  /etc/pcp/pmcd        0755 root root -"
        # pmcd.conf is (re)deployed on every pmcd start via ExecStartPre — a
        # tmpfiles "C" rule only copies when absent, so it would go stale on
        # config changes. pmcd may rewrite this file at runtime, so it must be a
        # real writable copy, not a store symlink.
        "L+ /etc/pcp/labels      - - - - ${cfg.package}/share/pcp/etc/pcp/labels"
        "L+ /etc/pcp/pmie        - - - - ${cfg.package}/share/pcp/etc/pcp/pmie"
        "L+ /etc/pcp/pmlogger    - - - - ${cfg.package}/share/pcp/etc/pcp/pmlogger"
        "L+ /etc/pcp/pmproxy     - - - - ${cfg.package}/share/pcp/etc/pcp/pmproxy"
        "L+ /etc/pcp/derived     - - - - ${cfg.package}/share/pcp/etc/pcp/derived"
      ];

      # ─── pmcd (collector daemon) ─────────────────────────────────────────
      systemd.services.pmcd = {
        description = "Performance Co-Pilot Collector Daemon";
        wantedBy = [ "multi-user.target" ];
        after = [ "network.target" ];
        wants = [ "network.target" ];
        environment = pcpEnv;
        # Restart pmcd whenever the generated PMDA config changes (adding/removing
        # a PMDA) — pmcd reads pmcd.conf only at startup.
        restartTriggers = [ pmcdConf ];
        serviceConfig = {
          Type = if hasBccPmda then "simple" else "forking";
          # Deploy a fresh writable pmcd.conf before each start.
          ExecStartPre = "${pkgs.coreutils}/bin/install -Dm0644 ${pmcdConf} /etc/pcp/pmcd/pmcd.conf";
          ExecStart = "${cfg.package}/libexec/pcp/bin/pmcd"
            + optionalString hasBccPmda " -f -q 60 -t 30";
          Restart = "on-failure";
          RuntimeDirectory = "pcp";
          StateDirectory = "pcp";
        } // optionalAttrs (!hasBccPmda) {
          PIDFile = "/run/pcp/pmcd.pid";
        } // optionalAttrs hasBccPmda {
          TimeoutStartSec = "300";  # BCC eBPF compilation can take minutes
        } // pmcdHardening // ipFiltering;
      };

      # ─── pmlogger (archive logger) ───────────────────────────────────────
      # pmlogger_check reads the control file, generates config.default via
      # pmlogconf, starts pmlogger daemons, then exits (hence Type=oneshot).
      systemd.services.pmlogger = mkIf cfg.pmlogger.enable {
        description = "Performance Co-Pilot Archive Logger";
        wantedBy = [ "multi-user.target" ];
        after = [ "pmcd.service" ];
        bindsTo = [ "pmcd.service" ];
        environment = pcpEnv;
        path = with pkgs; [ coreutils gawk gnused gnugrep hostname findutils util-linux procps cfg.package ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = "${cfg.package}/libexec/pcp/bin/pmlogger_check -V";
          ExecStop = "${cfg.package}/libexec/pcp/bin/pmlogger_check -s -V";
          User = "pcp";
          Group = "pcp";
          StateDirectory = "pcp";
          LogsDirectory = "pcp/pmlogger";
          TimeoutStartSec = "120";
        };
      };

      # ─── pmie (inference engine) ─────────────────────────────────────────
      systemd.services.pmie = mkIf cfg.pmie.enable {
        description = "Performance Co-Pilot Inference Engine";
        wantedBy = [ "multi-user.target" ];
        after = [ "pmcd.service" ];
        bindsTo = [ "pmcd.service" ];
        environment = pcpEnv;
        path = with pkgs; [ coreutils gawk gnused gnugrep hostname findutils util-linux procps cfg.package ];
        serviceConfig = {
          Type = "forking";
          ExecStart = "${cfg.package}/libexec/pcp/bin/pmie_check";
          Restart = "on-failure";
          User = "pcp";
          Group = "pcp";
          StateDirectory = "pcp";
          LogsDirectory = "pcp/pmie";
        };
      };

      # ─── pmie-rules (custom inference rules, dedicated instance) ──────────
      # Runs our own pmie against services.pcp.pmieConfig, separate from
      # pmie_check. Type=simple + `-f` keeps pmie in the foreground so systemd
      # tracks it and `print` firings stream to the journal.
      systemd.services.pmie-rules = mkIf (cfg.pmie.enable && cfg.pmieConfig != "") {
        description = "Performance Co-Pilot Inference Engine (custom atreides rules)";
        wantedBy = [ "multi-user.target" ];
        after = [ "pmcd.service" ];
        bindsTo = [ "pmcd.service" ];
        environment = pcpEnv;
        path = with pkgs; [ coreutils cfg.package ];
        serviceConfig = {
          Type = "simple";
          ExecStart = "${cfg.package}/bin/pmie -f -c ${customPmieFile} -l /var/log/pcp/pmie/atreides.log";
          Restart = "on-failure";
          RestartSec = "10";
          User = "pcp";
          Group = "pcp";
          StateDirectory = "pcp";
          LogsDirectory = "pcp/pmie";
        };
      };

      # ─── pcp-hotproc (apply hotproc predicate at runtime) ────────────────
      # Best-effort: filters the hotproc.* metric tree to the compositor/shell
      # so the desktop_rss rule tracks only those. Non-fatal if pmstore rejects
      # the value — hotproc.* just reports no instances then.
      systemd.services.pcp-hotproc = mkIf (cfg.hotprocPredicate != "" && (cfg.pmdas ? proc)) {
        description = "Configure PCP hotproc predicate (kwin/plasmashell tracking)";
        wantedBy = [ "multi-user.target" ];
        after = [ "pmcd.service" ];
        bindsTo = [ "pmcd.service" ];
        environment = pcpEnv;
        path = with pkgs; [ coreutils cfg.package ];
        # Re-run when the collector config changes (e.g. proc PMDA added).
        restartTriggers = [ pmcdConf ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        # The proc PMDA may take a moment to be ready after pmcd starts; retry.
        script = ''
          for i in $(seq 1 30); do
            if pmstore hotproc.control.config '${cfg.hotprocPredicate}' >/dev/null 2>&1; then
              echo "pcp-hotproc: predicate applied"
              exit 0
            fi
            sleep 2
          done
          echo "pcp-hotproc: could not apply predicate (proc PMDA not ready?)" >&2
        '';
      };

      # ─── pmproxy (REST API gateway) ──────────────────────────────────────
      systemd.services.pmproxy = mkIf cfg.pmproxy.enable {
        description = "Performance Co-Pilot REST API Proxy";
        wantedBy = [ "multi-user.target" ];
        after = [ "pmcd.service" ];
        bindsTo = [ "pmcd.service" ];
        environment = pcpEnv;
        serviceConfig = {
          Type = "forking";
          ExecStart = "${cfg.package}/libexec/pcp/bin/pmproxy";
          PIDFile = "/run/pcp/pmproxy.pid";
          Restart = "on-failure";
        } // pmproxyHardening // ipFiltering;
      };

      # ─── Maintenance timers ──────────────────────────────────────────────
      systemd.timers.pmlogger-daily = mkIf cfg.pmlogger.enable {
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnCalendar = "*-*-* 00:10:00";
          Persistent = true;
        };
      };
      systemd.services.pmlogger-daily = mkIf cfg.pmlogger.enable {
        description = "PCP Logger Daily Maintenance";
        environment = pcpEnv;
        path = with pkgs; [ coreutils gawk gnused gnugrep hostname findutils util-linux procps cfg.package ];
        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${cfg.package}/libexec/pcp/bin/pmlogger_daily";
        };
      };

      systemd.timers.pmie-daily = mkIf cfg.pmie.enable {
        wantedBy = [ "timers.target" ];
        timerConfig = {
          OnCalendar = "*-*-* 00:08:00";
          Persistent = true;
        };
      };
      systemd.services.pmie-daily = mkIf cfg.pmie.enable {
        description = "PCP Inference Engine Daily Maintenance";
        environment = pcpEnv;
        path = with pkgs; [ coreutils gawk gnused gnugrep hostname findutils util-linux procps cfg.package ];
        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${cfg.package}/libexec/pcp/bin/pmie_daily";
        };
      };

      # Firewall (off by default — loopback clients don't need it)
      networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall (
        [ constants.ports.pmcd ] ++ optional cfg.pmproxy.enable constants.ports.pmproxy
      );
    })
  ];
}

# <> #
